config_setting(
    name = "develop",
    values = {
        "define": "environment=develop",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "production",
    values = { 
        "define": "environment=production",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "adhoc",
    values = { 
        "define": "environment=adhoc",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "ios13",
    values = { 
        "ios_minimum_os": "13.0",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "ios12",
    values = { 
        "ios_minimum_os": "12.0",
    },
    visibility = ["//visibility:public"],
)